// <auto-generated />
using System;
using ControleBiblioteca.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleBiblioteca.Api.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    partial class BibliotecaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("ControleBiblioteca.Api.Models.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataDevolucaoReal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("LivroId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MultaAtraso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusEmprestimo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("ControleBiblioteca.Api.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoPublicacao = 2024,
                            Autor = "Microsoft Press",
                            Categoria = "Programação",
                            Editora = "TechBooks",
                            Isbn = "978-1-01",
                            QuantidadeDisponivel = 10,
                            QuantidadeTotal = 10,
                            Titulo = "Arquitetura de Software com C# e MVVM"
                        },
                        new
                        {
                            Id = 2,
                            AnoPublicacao = 2023,
                            Autor = "OpenSource Ed",
                            Categoria = "Infraestrutura",
                            Editora = "TechBooks",
                            Isbn = "978-1-02",
                            QuantidadeDisponivel = 5,
                            QuantidadeTotal = 5,
                            Titulo = "Guia Avançado de Linux e Administração de Servidores"
                        },
                        new
                        {
                            Id = 3,
                            AnoPublicacao = 2025,
                            Autor = "CyberSec",
                            Categoria = "Segurança da Informação",
                            Editora = "Security Press",
                            Isbn = "978-1-03",
                            QuantidadeDisponivel = 4,
                            QuantidadeTotal = 4,
                            Titulo = "Ethical Hacking e Penetration Testing"
                        },
                        new
                        {
                            Id = 4,
                            AnoPublicacao = 2025,
                            Autor = "Science Press",
                            Categoria = "Tecnologias Emergentes",
                            Editora = "Quantum Labs",
                            Isbn = "978-1-04",
                            QuantidadeDisponivel = 3,
                            QuantidadeTotal = 3,
                            Titulo = "Fundamentos de Computação Quântica e IA"
                        },
                        new
                        {
                            Id = 5,
                            AnoPublicacao = 2024,
                            Autor = "TechBooks",
                            Categoria = "Programação",
                            Editora = "TechBooks",
                            Isbn = "978-1-05",
                            QuantidadeDisponivel = 8,
                            QuantidadeTotal = 8,
                            Titulo = "Desenvolvimento de APIs RESTful com .NET 8"
                        },
                        new
                        {
                            Id = 6,
                            AnoPublicacao = 2009,
                            Autor = "Robert C. Martin",
                            Categoria = "Engenharia de Software",
                            Editora = "Alta Books",
                            Isbn = "978-1-06",
                            QuantidadeDisponivel = 15,
                            QuantidadeTotal = 15,
                            Titulo = "Clean Code: Habilidades Práticas do Agile Software"
                        },
                        new
                        {
                            Id = 7,
                            AnoPublicacao = 2021,
                            Autor = "Kurose & Ross",
                            Categoria = "Infraestrutura",
                            Editora = "Pearson",
                            Isbn = "978-1-07",
                            QuantidadeDisponivel = 6,
                            QuantidadeTotal = 6,
                            Titulo = "Redes de Computadores e Internet"
                        },
                        new
                        {
                            Id = 8,
                            AnoPublicacao = 2013,
                            Autor = "Goodrich",
                            Categoria = "Programação",
                            Editora = "Bookman",
                            Isbn = "978-1-08",
                            QuantidadeDisponivel = 7,
                            QuantidadeTotal = 7,
                            Titulo = "Estruturas de Dados e Algoritmos em Python"
                        },
                        new
                        {
                            Id = 9,
                            AnoPublicacao = 2000,
                            Autor = "GoF",
                            Categoria = "Arquitetura de Software",
                            Editora = "Bookman",
                            Isbn = "978-1-09",
                            QuantidadeDisponivel = 5,
                            QuantidadeTotal = 5,
                            Titulo = "Design Patterns: Elementos de Software Orientado a Objetos"
                        },
                        new
                        {
                            Id = 10,
                            AnoPublicacao = 2017,
                            Autor = "Susan J. Fowler",
                            Categoria = "Arquitetura de Software",
                            Editora = "Novatec",
                            Isbn = "978-1-10",
                            QuantidadeDisponivel = 4,
                            QuantidadeTotal = 4,
                            Titulo = "Microsserviços Prontos Para a Produção"
                        });
                });

            modelBuilder.Entity("ControleBiblioteca.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StatusAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "111.111.111-11",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "erick.araujo@aluno.senai.br",
                            NomeCompleto = "Erick Silva Fernandes de Araujo",
                            StatusAtivo = true,
                            Telefone = "31999999999"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "222.222.222-22",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "frederico.instrutor@senai.br",
                            NomeCompleto = "Frederico Aguiar",
                            StatusAtivo = true,
                            Telefone = "31988888888"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "333.333.333-33",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ada.lovelace@tech.com",
                            NomeCompleto = "Ada Lovelace",
                            StatusAtivo = true,
                            Telefone = "31977777777"
                        },
                        new
                        {
                            Id = 4,
                            Cpf = "444.444.444-44",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alan.turing@tech.com",
                            NomeCompleto = "Alan Turing",
                            StatusAtivo = true,
                            Telefone = "31966666666"
                        },
                        new
                        {
                            Id = 5,
                            Cpf = "555.555.555-55",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "linus.t@tech.com",
                            NomeCompleto = "Linus Torvalds",
                            StatusAtivo = true,
                            Telefone = "31955555555"
                        },
                        new
                        {
                            Id = 6,
                            Cpf = "666.666.666-66",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grace.h@tech.com",
                            NomeCompleto = "Grace Hopper",
                            StatusAtivo = true,
                            Telefone = "31944444444"
                        },
                        new
                        {
                            Id = 7,
                            Cpf = "777.777.777-77",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "margaret.h@tech.com",
                            NomeCompleto = "Margaret Hamilton",
                            StatusAtivo = true,
                            Telefone = "31933333333"
                        },
                        new
                        {
                            Id = 8,
                            Cpf = "888.888.888-88",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dennis.r@tech.com",
                            NomeCompleto = "Dennis Ritchie",
                            StatusAtivo = true,
                            Telefone = "31922222222"
                        },
                        new
                        {
                            Id = 9,
                            Cpf = "999.999.999-99",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tim.bl@tech.com",
                            NomeCompleto = "Tim Berners-Lee",
                            StatusAtivo = true,
                            Telefone = "31911111111"
                        },
                        new
                        {
                            Id = 10,
                            Cpf = "000.000.000-00",
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bjarne.s@tech.com",
                            NomeCompleto = "Bjarne Stroustrup",
                            StatusAtivo = true,
                            Telefone = "31900000000"
                        });
                });

            modelBuilder.Entity("ControleBiblioteca.Api.Models.Emprestimo", b =>
                {
                    b.HasOne("ControleBiblioteca.Api.Models.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleBiblioteca.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
